### ISSUE TITLE
Tab Not Updated After Closing Split Panes

### ISSUE THREAD

**Issue by lo-tp** [drmingdrmer/vim-tabbar#2]
At first, Thanks for this plugin.

After playing with it for a while I found a problem.

Steps to reproduce:

- Open 'a' file in a window.
- Open 'b' file in a splitpane in that same window.
- Close 'a' file.
- The tab still shows title of 'a' coupled with that of 'b'.

**Comment by drmingdrmer** [comment]
May you provide what command exactly did you use to achieve these steps?
Since in vim there are several commands do similar things but the internal behaviors are different.
E.g. `close` could be closing a window(`:close`) or wipe a buffer(`:bwipeout`)

**Comment by lo-tp** [comment]
OS: Mojave
VIM Version: NVIM v0.3.4

Steps to Reproduce:
- nvim a.txt
- :split
- :e b.txt
- :q

Now the tab is still showing `a.txt  b.txt`.
At this moment, b.txt is not supposed to be shown.

**Comment by drmingdrmer** [comment]
`:q` does not remove a buffer, it just closes a window.
The buffer for `b.txt` is still in memory. You can see it in `:buffers`.

This is what this plugin does: if a buffer is not removed(by `:bdelete` or `:bwipe`), it will be displayed on the buffer tab.

**Comment by lo-tp** [comment]
So is it correct to say that the content of the tab is the complete list of opened buffers in lieu of the files currently shown ?

**Comment by drmingdrmer** [comment]
Yes. It is a list of the opened files. Not a list of visible files.
Showing all visible files makes little sense.

The tab bar displays different color for invisible files(grey), the file currently focused(white bg) and the visible but not focused files(white fg):
![image](https://user-images.githubusercontent.com/44069/56863643-9b956100-69eb-11e9-8aa2-e40016dbcd6b.png)
